license="MIT"
modLoader="javafml"
loaderVersion="[47,)"
issueTrackerURL="https://github.com/DynamicTreesTeam/DynamicTrees/issues"

[[mods]]
modId="dtenhanced_mushrooms"
version="${file.jarVersion}"
displayName="Dynamic Trees for Enhanced Mushrooms"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dynamictrees"
logoFile="logo.png"
credits=""
authors="Wenxin2"
description='''
Adds Dynamic Trees compatibility for Enhanced Mushrooms.
'''

[[dependencies.dtenhanced_mushrooms]]
    modId="forge"
    mandatory=true
    versionRange="[47.1.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtenhanced_mushrooms]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.dtenhanced_mushrooms]]
    modId="dynamictrees"
    mandatory=true
    versionRange="[1.3.6,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dtenhanced_mushrooms]]
    modId="dynamictreesplus"
    mandatory=true
    versionRange="[1.2.0-BETA1,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dtenhanced_mushrooms]]
    modId="enhanced_mushrooms"
    mandatory=true
    versionRange="[5.0.0,)"
    ordering="AFTER"
    side="BOTH"
